name: "Playwright Tests"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  plawright-test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.56.1-jammy
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install node js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: "Install dependencies"
        run: npm ci
      - name: "Run tests"
        run: npm test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          HTTP_USERNAME: ${{ secrets.HTTP_USERNAME }}
          HTTP_PASSWORD: ${{ secrets.HTTP_PASSWORD }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      - name: "Upload Playwright Report"
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 5